sudo:
  required

dist:
  trusty

addons:
  apt:
    packages:
      - pandoc

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

before_install:
  - openssl aes-256-cbc -K $encrypted_f6621a710d15_key -iv $encrypted_f6621a710d15_iv -in .credentials.json.enc -out .credentials.json -d

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls

before_deploy:
  - pandoc --version
  - pandoc -f markdown_github -t rst -o README.rst README.md
  - mv README.rst README.md

deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: g3IB0X3yUerOyPNJ/qsNwHgYTsFJEzA2myO4zEy3v2AzM1HZKjLtFZzCwGA28hZpqEAGZ+srkMRAEc1fF9AwzK3q6o8QS6FB35z+dYNtGByiuU95ySrkFPpyfCBWJ7Fr4Mxq76S09SmeC+hFOtOww6VeEqyW7Wa+8o0G09NUEN+W8uD264qFIqoeaYNYGVVEiFs9ZchhT6DWwhBsTss7P6L1fXbQrbWjhD0mumbtFeFAuHoUDEndpgxMfeZQrXLS4iNVlpgAQ7zGZmCvUBfD8Pu1D4gGmAY8dBW+ELKuMFRENk4FYLU7Skq5/zaELfp3CHhy4gI35qSey81W7zWQt/QStfSTZ8JkKvZSXEJ7JYoU8O07SdzMH51cG1wnrh/w1XDK+C2aNBDKuPfjJzEJqc7H1eIgchOxEDfK/ZzuufIT51xoP+GlYHhs8PK2NzU78v2iCyuv/tg7mFoQJzfdc2s/VqDxDzTamu/HBd6MBn1gwwa92pOVTzd6LP81LnLyNRfw/NBxH4/31rWDl9MdpGPqq9pADjfmnEHtGHzzt9hwurLtJOsXWER6vee3cO1hb+2G9FxvLXFJXlWXrZpjSzezjHChpP/xfuU1EXOiFWpKf+GfqCLnAExbNdi+i2EnDEbTdkfMsjwNwNwScfRvOnOtneaCVxr1rnyAzUfa4Vw=
