sudo:
  required

dist:
  trusty

addons:
  apt:
    packages:
      - pandoc

language:
  python

python:
  - 2.7
  - 3.3
  # - 3.4
  - 3.5
  - 3.6

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

before_install:
  - openssl aes-256-cbc -K $encrypted_3343fdf878cf_key -iv $encrypted_3343fdf878cf_iv -in .credentials.json.enc -out .credentials.json -d

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls

before_deploy:
  - pandoc --version
  - pandoc -f markdown_github -t rst -o README.rst README.md
  - mv README.rst README.md

deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: hmjc1R3LVbPZ0HK73QlW3HfGAAxuAXTRSZtn/hR1aIda5CACyfa67s4P7dLE8sV4tKO52L/hqxgpm+Tp1ssp3GnlFedcoROvqkm22JCHjDlSyu9VpYt/lTwCY1OKBennGjY9TfvfAJWup+e+kIDmLOBFTtCOvvEhHD7agtob14SbV65ELmzpPsP/GlG7n6hNN6B97HsjXhjdlDC6wR2yfAodkjIHMR2l5g5BnySVZ0QNIzIlpMILUXHb0mm2PfZU2mr2fsTDkpj/k95yCANoC0gOFzYnewohriEX6NA4xiD4R/sxsCVLcfOOrZPoUGtFt42K+wyMiJG3/N6quR4rPoLkaKVt5yHcrhxGboYDXs6hPEnf3CHJ4ENxi6xDZI4RvYCrEbTb9OqGqv8ci2C44H27c/qBTjulm4sb9mUIJnurR+D+U7TO6GNj52xrIS8wvjl2EQ0srrZll2BKhXzsLtn7qa24pyyrHW+AU3NZmEq+1nJG+X1F8e1VEBZKb3P+ft3lJTMl7bnOlc95sTWFn/CMiZb3itGT0pEbFWGw3Nrl1JAUfJSCr6kEkjqMvRyiWqCMsjKltAfQ7KqV6mW6zptOKn1xgyPysmQJqL+qFWRR3hagzPqIy/EoMbaQDJ9ISx8hbDroCxDDEHtxRy2og0oVgbZTk+7j4aKEi3XrDUk=
